server:
  port: 8082
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/youyongpeng/config.git
          search-paths: /**
          username: youyongpeng
          password: YOUyongpeng@0
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/