server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: zzstc-web
  cloud:
    config:
      uri: http://localhost:8082
myname: 张三